services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab1-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lab1db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - '5432:5432'
    volumes:
      - "./docker-volumes/postgres-volume:/var/lib/postgresql/data"
